### ISSUE TITLE
Local StakedCitadelVester.claimableBalance() Bug

### ISSUE THREAD

**Issue by mrbasado** [Citadel-DAO/citadel-contracts#49]
The claimableBalance function fails when running a local mainnet fork after using the deploy-local.js script. Example which caused the error: 
const vesting = Vesting__factory.connect(addresses[networkId].XCTDL_VESTING, signer);
let claimable = await vesting.claimableBalance(address);

Error below:
Contract call:       StakedCitadelVester#claimableBalance
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x26b862f640357268bd2d9e95bc81553a2aa81d7e

  Error: VM Exception while processing transaction: reverted with panic code 0x11 (Arithmetic operation underflowed or overflowed outside of an unchecked block)
      at StakedCitadelVester.claimableBalance (src/StakedCitadelVester.sol:115)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at HardhatNode.runCall (/Users/Meta/Documents/IdeaProjects/CTDL/citadel-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:615:20)
      at EthModule._callAction (/Users/Meta/Documents/IdeaProjects/CTDL/citadel-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:9)
      at HardhatNetworkProvider._sendWithLogging (/Users/Meta/Documents/IdeaProjects/CTDL/citadel-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at HardhatNetworkProvider.request (/Users/Meta/Documents/IdeaProjects/CTDL/citadel-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at JsonRpcHandler._handleRequest (/Users/Meta/Documents/IdeaProjects/CTDL/citadel-contracts/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)

**Comment by harleythedogC4** [comment]
I put in a PR to fix this problem a few days ago: https://github.com/Citadel-DAO/citadel-contracts/pull/44
